#!/usr/bin/env python3
"""
BIDS Knowledge Base Retriever (JSONL-based).

Drop-in replacement for the original txt/md keyword Retriever. Loads the
structured knowledge base generated by extract_kb.py (knowledge.jsonl,
relationships.jsonl, sources.jsonl) once at construction and serves
repeated queries from an in-memory index.

Public API (unchanged):
    retriever = Retriever("./knowledge")          # data_dir with the JSONL files
    result = retriever.retrieve("What is the task entity?", top_k=2)
    # result is always a formatted string -> passed to the LLM by the Planner

Architecture:
    User Query -> Planner -> Retriever.retrieve(query, top_k) -> LLM

Design notes:
  * Zero external dependencies (Python stdlib only).
  * Loading/parsing, indexing, scoring and formatting are kept in separate
    classes so the token scorer can later be swapped for embeddings.
  * All weights/fields are derived from the ACTUAL schema of the generated
    knowledge base (verified against knowledge.jsonl in this directory).
"""

import json
import logging
import math
import os
import re
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

logger = logging.getLogger(__name__)

# Knowledge base file names (relative to data_dir)
# KNOWLEDGE_FILE = "knowledge.jsonl"
KNOWLEDGE_FILE = "enriched_knowledge.jsonl"
RELATIONSHIPS_FILE = "relationships.jsonl"
SOURCES_FILE = "sources.jsonl"
REPORT_FILE = "processing_report.json"  # never used as retrieval content

# Fallback messages (stable strings, asserted by tests)
MSG_NO_KB = "Knowledge base file 'knowledge.jsonl' not found in {}."
MSG_EMPTY_KB = "The BIDS knowledge base is empty or could not be loaded."
MSG_EMPTY_QUERY = "An empty query was provided."
MSG_NO_MATCH = 'No relevant BIDS knowledge found for the query: "{}".'

# Queries whose best score falls below this (for a large KB) are treated
# as having no real match, avoiding boilerplate-driven noise for
# out-of-KB terms such as "Funding" or "SourceDatasets". The floor scales
# down with KB size so small knowledge bases still return real matches.
# Tuned for the issue-aware scoring scale (~0-90, well-matched records
# score in the tens; weak generic token matches score in the low single
# digits).
MIN_BEST_SCORE = 3.0

# Issue-aware retrieval ----------------------------------------------------
# When the planner passes a serialized issue object (compact_json), the
# retriever must NOT treat the flat text as one equally-weighted bag of
# words. These keys are recognized while parsing the serialization so that
# the rule_id / field / severity become structured, highly-weighted query
# components instead of ordinary tokens.
_KNOWN_ISSUE_KEYS = frozenset({
    "severity", "rule_id", "message", "field", "path",
    "suffix", "datatype", "issues", "sidecar_fields",
    "line", "lines", "fix_label", "fix_action", "mirrored",
})

# Issue keys whose values carry no retrieval signal (they only exist in the
# error object as structural bookkeeping) and would otherwise pollute the
# query with coincidental tokens such as "line" / "lines".
_NONSEMANTIC_ISSUE_KEYS = frozenset({
    "line", "lines", "fix_label", "fix_action", "mirrored", "sidecar_fields",
})


def _parse_query(query: str) -> dict:
    """
    Attempt to parse a serialized issue object out of a query string.

    The BIDS planner currently passes ``"{user_input} {compact_json(issue)}"``
    to ``Retriever.retrieve()``. ``compact_json`` renders the issue as
    ``severity:err rule_id:JSON_SCHEMA_VALIDATION_ERROR message:... field:...``.
    Recognizing this structure lets the retriever weight the *role* of each
    piece of the issue (rule id, field name, message, severity) instead of
    scoring every word identically.

    Returns a dict of the recognized semantic components (e.g.
    ``{"rule_id": "...", "field": "...", "message_text": "...",
    "severity": "err", "general_text": "Explain this to me."}``), or an
    empty dict when the query is a plain natural-language string (no issue
    serialization detected) - in which case the caller falls back to
    standard full-text scoring.
    """
    if not query or not query.strip():
        return {}

    keys_alt = "|".join(
        re.escape(k) for k in sorted(_KNOWN_ISSUE_KEYS, key=len, reverse=True)
    )
    field_re = re.compile(rf"(?:^|\s)({keys_alt}):")
    matches = list(field_re.finditer(query))
    if len(matches) < 2:
        return {}

    root_fields: Dict[str, str] = {}
    for i, m in enumerate(matches):
        root_fields[m.group(1)] = query[m.end(): matches[i + 1].start() if i + 1 < len(matches) else len(query)].strip()

    # Extract the semantic values; a later match with the same key (e.g. the
    # nested issue inside "issues:[...]") legitimately overwrites the outer
    # one, so the innermost issue wins.
    result: Dict[str, str] = {}
    for key in ("rule_id", "field", "severity", "message", "path",
                "suffix", "datatype"):
        if key in _NONSEMANTIC_ISSUE_KEYS:
            continue
        value = _clean_issue_value(root_fields.get(key))
        if value:
            result["message_text" if key == "message" else key] = value

    # nested issues (sample_issue_003 style): lift the inner issue's fields
    nested = root_fields.get("issues", "")
    if nested and not result.get("rule_id"):
        nested_rid = re.search(r"\brule_id:(\S+)", nested)
        nested_ft = re.search(r"\bfield:(\S+)", nested)
        if nested_rid:
            result["rule_id"] = _clean_issue_value(nested_rid.group(1).rstrip("}"))
        if nested_ft:
            result["field"] = _clean_issue_value(nested_ft.group(1).rstrip("}"))

    general_end = matches[0].start() if matches else 0
    general_text = query[:general_end].strip()
    if general_text:
        result["general_text"] = general_text

    return result


def _clean_issue_value(value: Any) -> str:
    """Strip/skip issue values that carry no retrieval signal.

    Sentence-worthy values must survive untouched (they are scored), while
    JSON bookkeeping placeholders such as ``"null"`` or ``"none"`` are
    dropped so they never leak tokens like 'null' into the query.
    """
    if value is None:
        return ""
    text = str(value).strip()
    if not text or text.lower() in ("null", "none"):
        return ""
    return text


def _issue_structured(issue: dict) -> dict:
    """
    Build the structured retrieval components directly from an issue dict.

    Mirrors the output shape of ``_parse_query`` (keys ``rule_id``,
    ``field``, ``severity``, ``message_text``, ``path``, ``suffix``,
    ``datatype``) but without the lossy string round-trip, so callers that
    already hold the structured issue (e.g. ``Retriever.retrieve_issue``)
    can pass exact values instead of re-serializing and re-parsing them.
    """
    if not isinstance(issue, dict) or not issue:
        return {}

    combined: Dict[str, Any] = dict(issue)
    inner = issue.get("issues")
    if isinstance(inner, list) and inner:
        inner_issue = inner[0]
        if isinstance(inner_issue, dict):
            for key, value in inner_issue.items():
                combined.setdefault(key, value)

    result: Dict[str, str] = {}
    for key in ("rule_id", "field", "severity", "message", "path",
                "suffix", "datatype"):
        value = _clean_issue_value(combined.get(key))
        if value:
            result["message_text" if key == "message" else key] = value
    return result


# ====================================================================
# Data model
# ====================================================================


class KnowledgeRecord:
    """
    One record from knowledge.jsonl.

    Maps the real top-level fields of the generated knowledge base:
        id, knowledge_type, title, summary, retrieval_text, scope,
        source, raw_content, bids_version, schema_version, and the
        optional rule fields: requirements, conditions, allowed_values,
        severity, expression, unit.
    """

    __slots__ = (
        "id", "knowledge_type", "title", "summary", "retrieval_text",
        "source", "scope", "raw_content", "bids_version", "schema_version",
        "requirements", "conditions", "allowed_values",
        "severity", "expression", "unit",
    )

    def __init__(self, data: Dict[str, Any]) -> None:
        self.id: str = str(data.get("id", "") or "")
        self.knowledge_type: str = str(data.get("knowledge_type", "unknown"))
        self.title: str = str(data.get("title", "") or "")
        self.summary: str = str(data.get("summary", "") or "")
        self.retrieval_text: str = str(data.get("retrieval_text", "") or "")
        self.source: Dict[str, Any] = data.get("source") or {}
        self.scope: Dict[str, Any] = data.get("scope") or {}
        self.raw_content: Any = data.get("raw_content")
        self.bids_version: str = str(data.get("bids_version", "") or "")
        self.schema_version: str = str(data.get("schema_version", "") or "")
        self.requirements: Any = data.get("requirements")
        self.conditions: Any = data.get("conditions")
        self.allowed_values: Any = data.get("allowed_values")
        self.severity: Any = data.get("severity")
        self.expression: Any = data.get("expression")
        self.unit: Any = data.get("unit")

    # -- searchable representation ------------------------------------

    def build_search_blocks(self) -> List[Tuple[str, str, float]]:
        """
        Build the searchable representation of this record as a list of
        ``(label, text, weight)`` tuples.

        Weights reflect how discriminating each field is:
        * the rules/errors ``code`` (``requirements.code``) and the record
          id are the most specific identifiers;
        * free-text descriptions are the least specific.
        """
        blocks: List[Tuple[str, str, float]] = []

        def add(label: str, text: Any, weight: float) -> None:
            text = self._normalize(text)
            if text:
                blocks.append((label, text, weight))

        add("id", self.id, 4.0)
        add("title", self.title, 3.0)
        add("scope", self._flatten(self.scope), 3.0)
        add("requirements", self._flatten(self.requirements), 2.5)
        # The rules/errors code (e.g. "JSON_SCHEMA_VALIDATION_ERROR",
        # "WRONG_NEW_LINE") is the single most identity-bearing check value.
        if isinstance(self.requirements, dict) and self.requirements.get("code"):
            add("code", str(self.requirements["code"]), 5.0)
        add("allowed_values", self._flatten(self.allowed_values), 2.0)
        add("conditions", self._flatten(self.conditions), 2.0)
        add("summary", self.summary, 1.5)
        add("retrieval", self.retrieval_text, 1.5)
        add("expression", self.expression, 1.5)
        add("severity", self.severity, 1.0)
        add("unit", self.unit, 1.0)
        add("raw_content", json.dumps(self.raw_content, ensure_ascii=False), 0.8)

        return blocks

    def identity_text(self) -> str:
        """Compact text of the most identity-bearing fields (id/title/scope)."""
        return self._normalize(" ".join([
            self.id,
            self.title,
            self._flatten(self.scope),
        ]))

    # -- helpers --------------------------------------------------------

    @staticmethod
    def _normalize(text: Any) -> str:
        """
        Normalize text for matching, lowercase and treat '_' as a word
        separator (BIDS ids use it). CamelCase is split first so that an
        identifier such as ``ReferencesAndLinks`` becomes the word phrase
        ``references and links`` and can be matched against tokens like
        ``references`` / ``links`` that appear separately in KB records.
        """
        text = str(text or "")
        text = re.sub(r"([a-z])([A-Z])", r"\1 \2", text)
        text = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1 \2", text)
        return re.sub(r"[^a-z0-9 ]", " ", text.lower()).strip()

    @classmethod
    def _flatten(cls, value: Any) -> str:
        """Serialize arbitrary JSON values into a flat searchable string."""
        if value is None:
            return ""
        if isinstance(value, str):
            return value
        if isinstance(value, dict):
            return " ".join(
                f"{k}: {cls._flatten(v)}" for k, v in value.items()
            )
        if isinstance(value, (list, tuple)):
            return " ".join(cls._flatten(v) for v in value)
        return str(value)


class RelationshipEdge:
    """One edge from relationships.jsonl."""

    __slots__ = ("source", "relation", "target", "source_reference", "confidence")

    def __init__(self, data: Dict[str, Any]) -> None:
        self.source: str = str(data.get("source", "") or "")
        self.relation: str = str(data.get("relation", "") or "")
        self.target: str = str(data.get("target", "") or "")
        self.source_reference: str = str(data.get("source_reference", "") or "")
        self.confidence: str = str(data.get("confidence", "explicit"))


# ====================================================================
# Scorer — lightweight token scoring with field-aware weights
# ====================================================================


class Scorer:
    """
    Field-aware token scorer for the BIDS knowledge base.

    Design goals (see the module docstring of the Retriever):
    * **Query-focused** — when the query contains a serialized issue, the
      structured components (rule_id, field, severity, message) are weighted
      by their semantic role instead of being flattened into one equally
      weighted bag of words.
    * **Field-aware** — a match in a high-value block (rule ``code``, id,
      title, scope) is worth much more than the same word in free-text
      ``summary`` or ``raw_content``.
    * **Resistant to generic-token false positives** — a token contributes
      once at full weight (its highest-value block); additional blocks add
      only a heavily damped bonus. This prevents words that happen to appear
      in several fields (e.g. "type", "value", "text") from accumulating a
      large cumulative score. Rare-but-irrelevant tokens are further damped
      by capping IDF.
    * **Issue-aware exact matching** — the rule code and field name extracted
      from the issue are matched against the record's identity and
      requirement code blocks, dominating any generic lexical overlap.

    A \u201cwhole-word\u201d match inside a block contributes
    ``1.5 * block_weight * idf`` for the single best block and at most two
    additional blocks contribute ``1.5 * min(block_weight, best * RATIO) *
    idf``, with the whole per-token contribution capped at
    ``MAX_TOKEN_CONTRIBUTION`` so one coincidental keyword can never
    dominate. Prefix matches only fire as a fallback when a token has no
    whole-word match anywhere, and contribute ``0.5 * block_weight * idf``.
    """

    # Additional per-block "decay" the same token gets for matching in more
    # than one block: extra blocks contribute at most this fraction of the
    # best block's contribution.
    EXTRA_BLOCK_RATIO = 0.12
    # Number of extra blocks (besides the best one) that may contribute.
    MAX_EXTRA_BLOCKS = 2
    # Base whole-word match multiplier.
    MATCH_MULTIPLIER = 1.5
    # Prefix fallback multiplier.
    PREFIX_MULTIPLIER = 0.5
    # Phrase bonus when the (message) text appears verbatim in a record.
    PHRASE_BONUS = 5.0
    # Hard cap on how much a *single* query token can contribute to a record
    # across all its blocks. Prevents one coincidence (e.g. "links" matching
    # BRAINVISION_LINKS_BROKEN's high-weight code block) from dominating the
    # ranking of an otherwise unrelated record.
    MAX_TOKEN_CONTRIBUTION = 8.0
    # Identifier words (extracted from rule_id / field / path / suffix) are
    # weak individual evidences: their *full phrase* match is what carries
    # meaning, and that is already rewarded by the structured bonuses. So
    # they are scored with a smaller multiplier and a tighter cap than words
    # appearing in the explanatory message text.
    IDENTIFIER_MULTIPLIER = 0.4
    MAX_IDENTIFIER_TOKEN_CONTRIBUTION = 3.0
    # Structured exact-match bonuses (issue-aware retrieval).
    RULE_ID_EXACT = 20.0
    RULE_ID_IN_TITLE = 15.0
    FIELD_IN_TITLE = 12.0
    FIELD_IN_ID = 10.0
    FIELD_IN_SUMMARY = 5.0
    SEVERITY_MATCH = 1.0
    # Field-phrase bonus when the record contains the *full* normalized field
    # name somewhere in a block, scaled by block importance. This rewards the
    # literal "ReferencesAndLinks" (or "EthicsApprovals") phrase - a much
    # stronger signal than a single coincidental token such as "links".
    FIELD_PHRASE_BONUS = {
        "code": 12.0,
        "title": 12.0,
        "id": 12.0,
        "scope": 10.0,
        "requirements": 10.0,
        "conditions": 8.0,
        "allowed_values": 8.0,
        "summary": 6.0,
        "retrieval": 6.0,
        "expression": 5.0,
        "raw_content": 5.0,
    }
    # BIDS identity bonus for recognized BIDS vocabulary in id/title/scope.
    BIDS_IDENTITY_BONUS = 0.5

    STOPWORDS = frozenset({
        "a", "an", "the", "and", "or", "but", "if", "then", "else",
        "in", "on", "at", "to", "of", "for", "with", "by", "from",
        "is", "are", "was", "were", "be", "been", "being", "it", "its",
        "this", "that", "these", "those", "as", "not", "do", "does",
        "did", "will", "would", "may", "might", "should", "shall",
        "what", "which", "who", "whom", "whose", "why", "how",
        "when", "where", "there", "here", "have", "has", "had",
        "can", "could", "than", "then", "so", "up", "out", "about",
        "into", "within", "without", "under", "over", "between",
        "after", "before", "during", "while", "such", "some", "any",
        "all", "each", "other", "please", "about", "give", "use",
        # Low-information modals / generic JSON-schema vocabulary that
        # would otherwise give near-equal scores to many records.
        "must", "can", "could", "might", "need", "needs", "shall",
        "contains", "containing", "item", "items", "array", "arrays",
        "placeholder", "todo", "value", "values", "list", "lists",
        "string", "boolean", "integer", "number", "numbers",
        "field", "fields", "type", "types", "key", "keys",
        "named", "called", "present", "absent",
        "contain", "include", "includes", "including", "specify",
        "specifies", "specified", "used", "uses", "using", "needed",
        "mean", "means", "make", "makes", "look", "looks",
        "explain", "me", "please", "wrong", "correct",
    })

    # BIDS-specific terms that deserve a small identity bonus when matched.
    # '_' is a word separator, so write tokens without underscores.
    BIDS_TERMS = frozenset({
        "sub", "ses", "subject", "session", "task", "acq", "acquisition",
        "run", "space", "desc", "suffix", "extension", "datatype",
        "modality", "bold", "events", "participant", "tsv", "json",
        "nii", "gz", "dataset", "anat", "func", "dwi", "fmap", "perf",
        "eeg", "meg", "ieeg", "pet", "mrs", "micr", "beh", "nirs",
        "motion", "t1w", "t2w", "cbf", "sbref", "echo", "flip", "dir",
        "inv", "hemi", "label", "fieldmap", "channels", "electrodes",
        "physio", "phenotype", "template", "entity", "sourcedata",
        "derivatives", "code", "stimuli", "sessions", "field",
        "metadata", "recommended", "required", "optional",
    })

    # Generic, low-information words that should never drive retrieval, even
    # though they appear frequently in messages. They are kept out of the
    # stopword set only so they can still participate in *exact* structured
    # matching (e.g. "type" inside a phrase) but are otherwise ignored here.
    GENERIC_TERMS = frozenset({
        "type", "value", "values", "text", "dataset", "information",
        "description", "string", "list", "lists", "array", "arrays",
        "field", "example", "correct", "must", "specify", "item", "items",
        "key", "keys", "default", "content", "include", "includes",
        "described", "valid", "formatting", "publications", "space",
        "format", "purposes", "according",
    })

    # whole-word / prefix matching against normalized (lowercased) text
    _WORD_RE = re.compile(r"\b[a-z0-9]+\b")

    @classmethod
    def tokenize(cls, text: str) -> List[str]:
        return [
            t for t in cls._WORD_RE.findall(KnowledgeRecord._normalize(text))
            if t not in cls.STOPWORDS and t not in cls.GENERIC_TERMS
        ]

    # -- Primary scoring entry point -------------------------------------

    @classmethod
    def query_terms(
        cls,
        query: str,
        structured_query: Optional[Dict[str, str]] = None,
    ) -> Tuple[List[str], Set[str], str]:
        """
        Compute the token lists and phrase source for a query.

        Returns ``(tokens, identifier_tokens, phrase_source)`` where
        ``tokens`` is the ordered list scored by ``Scorer.explain``,
        ``identifier_tokens`` is the subset with a lower multiplier, and
        ``phrase_source`` is the text checked for a verbatim substring
        bonus.

        This is extracted so that ``Retriever._candidate_indices`` can
        build exactly the same token set when pre-filtering candidates,
        guaranteeing that the accelerated path is a strict superset of
        what a full scan would score above zero.
        """
        identifier_tokens: Set[str] = set()
        message_tokens: List[str] = []
        phrase_source = query

        if structured_query:
            identifier_tokens = set(cls.tokenize(" ".join([
                structured_query.get("rule_id", ""),
                structured_query.get("field", ""),
                structured_query.get("path", ""),
                structured_query.get("suffix", ""),
                structured_query.get("datatype", ""),
            ])))
            message_tokens = [
                t for t in cls.tokenize(
                    structured_query.get("message_text", "")
                )
                if t not in identifier_tokens
            ]
            phrase_source = (
                structured_query.get("message_text")
                or structured_query.get("rule_id")
                or ""
            )
        else:
            message_tokens = cls.tokenize(query)

        return message_tokens + sorted(identifier_tokens), identifier_tokens, phrase_source

    @classmethod
    def score(
        cls,
        query: str,
        record: KnowledgeRecord,
        blocks: List[Tuple[str, str, float]],
        identity_text: str,
        idf_map: Optional[Dict[str, float]] = None,
        structured_query: Optional[Dict[str, str]] = None,
        precomputed: Optional[Dict[str, Any]] = None,
    ) -> float:
        """
        Score ``record`` for ``query``.

        When a serialized issue is recognized in ``query`` (pass it in
        ``structured_query``), the rule_id / field / severity are scored as
        structured exact matches and the message becomes the primary token
        source; the flat query string is *not* treated as plain text.

        ``rec_explanation = Scorer.explain(...)`` returns a dict detailing
        every contribution (used by ``Retriever.explain``).
        """
        if not query or not query.strip():
            return 0.0

        inst = cls.explain(
            query, record, blocks, identity_text, idf_map, structured_query,
            precomputed,
        )
        return inst["total"]

    @classmethod
    def explain(
        cls,
        query: str,
        record: KnowledgeRecord,
        blocks: List[Tuple[str, str, float]],
        identity_text: str,
        idf_map: Optional[Dict[str, float]] = None,
        structured_query: Optional[Dict[str, str]] = None,
        precomputed: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Return a dict with a full, auditable scoring breakdown:

        ``total``, ``structured`` (list of exact-match contributions),
        ``tokens`` (per-token contributions with their best block), and
        ``phrases``. Used by ``Retriever.explain`` and internally by
        ``score``.

        ``precomputed`` optionally carries per-record lookup structures
        (``block_words``: word set per block, ``phrase_text``: normalized
        title+summary+retrieval text, normalized title/id/summary and their
        token sets) so a query never re-normalizes the same record. When it
        is omitted the values are derived on the fly and the scoring result
        is identical.
        """
        idf_map = idf_map or {}
        breakdown: Dict[str, Any] = {
            "total": 0.0,
            "structured": [],
            "tokens": [],
            "phrases": [],
        }

        # -- 0. Cached per-record lookups (see Retriever._build_inverted_index)
        block_words: Optional[List[Set[str]]] = None
        phrase_text = ""
        rec_id = ""
        rec_title = ""
        rec_summary = ""
        title_tokens: Set[str] = set()
        id_tokens: Set[str] = set()
        summary_tokens: Set[str] = set()
        if precomputed:
            block_words = precomputed.get("block_words")
            phrase_text = precomputed.get("phrase_text", "")
            rec_id = precomputed.get("rec_id", "")
            rec_title = precomputed.get("rec_title", "")
            rec_summary = precomputed.get("rec_summary", "")
            title_tokens = precomputed.get("title_tokens") or set()
            id_tokens = precomputed.get("id_tokens") or set()
            summary_tokens = precomputed.get("summary_tokens") or set()

        def _norm(kind: str) -> str:
            if precomputed:
                return {"rec_id": rec_id, "rec_title": rec_title,
                        "rec_summary": rec_summary}[kind]
            if kind == "rec_id":
                return KnowledgeRecord._normalize(record.id)
            if kind == "rec_title":
                return KnowledgeRecord._normalize(record.title)
            return KnowledgeRecord._normalize(record.summary)

        def _word_set(kind: str) -> Set[str]:
            if precomputed:
                return {"rec_title": title_tokens, "rec_id": id_tokens,
                        "rec_summary": summary_tokens}[kind]
            return set(cls._WORD_RE.findall(_norm(kind)))

        # -- 1. Structured, issue-aware exact matches ---------------------
        if structured_query:
            sq = structured_query
            rule_code = ""
            if isinstance(record.requirements, dict):
                rc = record.requirements.get("code")
                if rc:
                    rule_code = KnowledgeRecord._normalize(str(rc))

            rule_id = KnowledgeRecord._normalize(sq.get("rule_id", "")).strip()
            if rule_id:
                if rule_code and rule_id == rule_code:
                    breakdown["structured"].append({
                        "type": "rule_id_exact",
                        "bonus": cls.RULE_ID_EXACT,
                        "details": f"issue rule_id == requirements.code ('{rule_id}')",
                    })
                    breakdown["total"] += cls.RULE_ID_EXACT
                elif rule_id == _norm("rec_id"):
                    breakdown["structured"].append({
                        "type": "rule_id_exact",
                        "bonus": cls.RULE_ID_EXACT,
                        "details": f"issue rule_id == record id ('{rule_id}')",
                    })
                    breakdown["total"] += cls.RULE_ID_EXACT
                elif rule_id and rule_id in _norm("rec_title"):
                    breakdown["structured"].append({
                        "type": "rule_id_in_title",
                        "bonus": cls.RULE_ID_IN_TITLE,
                        "details": f"issue rule_id found in record title ('{rule_id}')",
                    })
                    breakdown["total"] += cls.RULE_ID_IN_TITLE

            field = KnowledgeRecord._normalize(sq.get("field", "")).strip()
            if field:
                field_tokens = [
                    t for t in cls._WORD_RE.findall(field)
                    if t not in cls.STOPWORDS and t not in cls.GENERIC_TERMS
                ]
                field_bonus = 0.0
                field_why = ""
                if field_tokens:
                    # (a) Full normalized field phrase present verbatim in a
                    # block (e.g. "references and links" - the whole
                    # identifier, not a coincidental single word). Matched
                    # on whole words so a field like "age" cannot score a
                    # record merely because "mp2rage" contains it.
                    for label, text, _weight in blocks:
                        if cls._phrase_present(field, text):
                            bonus = cls.FIELD_PHRASE_BONUS.get(label, 5.0)
                            if bonus > field_bonus:
                                field_bonus = bonus
                                field_why = f"{label} (full '{field}' phrase)"
                    # (b) All field-name tokens present in identity/summary.
                    if all(ft in _word_set("rec_title") for ft in field_tokens):
                        if cls.FIELD_IN_TITLE > field_bonus:
                            field_bonus = cls.FIELD_IN_TITLE
                            field_why = "record title"
                    if all(ft in _word_set("rec_id") for ft in field_tokens):
                        if cls.FIELD_IN_ID > field_bonus:
                            field_bonus = cls.FIELD_IN_ID
                            field_why = "record id"
                    if all(ft in _word_set("rec_summary") for ft in field_tokens):
                        if cls.FIELD_IN_SUMMARY > field_bonus:
                            field_bonus = cls.FIELD_IN_SUMMARY
                            field_why = "summary"
                if field_bonus > 0:
                    breakdown["structured"].append({
                        "type": "field_exact",
                        "bonus": float(field_bonus),
                        "details": f"issue field '{field}' matched in {field_why}",
                    })
                    breakdown["total"] += float(field_bonus)

            issue_sev = (sq.get("severity", "") or "").lower().strip()
            if issue_sev:
                sev_expect = "error" if issue_sev == "err" else issue_sev
                rec_sev = str(record.severity or "").lower().strip()
                if sev_expect and rec_sev and sev_expect == rec_sev:
                    breakdown["structured"].append({
                        "type": "severity_match",
                        "bonus": cls.SEVERITY_MATCH,
                        "details": f"issue severity '{issue_sev}' == record severity '{rec_sev}'",
                    })
                    breakdown["total"] += cls.SEVERITY_MATCH

        # -- 2. Token source -------------------------------------------------
        # Issue queries: draw tokens from the semantic components only (rule
        # id, field, message, path, suffix). Plain queries: use the whole text.
        # The token set is computed by ``query_terms`` so that the
        # Retriever's candidate prefilter scores exactly the same tokens.
        tokens, identifier_tokens, phrase_source = cls.query_terms(
            query, structured_query
        )
        if not tokens and not breakdown["structured"]:
            return breakdown

        is_identifier = set(identifier_tokens)

        # -- 3. Token matches per block (best block + damped extras) --------
        for token in tokens:
            variants = cls._match_variants(token)
            idf = idf_map.get(token, 1.0)
            # Per-block match status. ``src`` is the text or its precomputed
            # word set, used for the whole-word and prefix checks below.
            if block_words:
                matches = [
                    (label, weight, any(v in block_words[i] for v in variants),
                     block_words[i])
                    for i, (label, _text, weight) in enumerate(blocks)
                ]
            else:
                matches = [
                    (label, weight,
                     any(cls._whole_word(v, text) for v in variants), text)
                    for label, text, weight in blocks
                ]

            contributions = [
                weight * idf for _label, weight, is_whole, _src in matches
                if is_whole
            ]
            if contributions:
                contributions.sort(reverse=True)
                best = contributions[0]
                token_score = cls.MATCH_MULTIPLIER * best
                extras = contributions[1: cls.MAX_EXTRA_BLOCKS + 1]
                for e in extras:
                    token_score += cls.MATCH_MULTIPLIER * min(
                        e, best * cls.EXTRA_BLOCK_RATIO
                    )
                # Identifier words are weak evidence on their own (their
                # whole phrase is what matters) - use a distinct, smaller
                # multiplier and cap for them.
                if token in is_identifier:
                    token_score = min(
                        token_score * cls.IDENTIFIER_MULTIPLIER,
                        cls.MAX_IDENTIFIER_TOKEN_CONTRIBUTION,
                    )
                else:
                    token_score = min(token_score, cls.MAX_TOKEN_CONTRIBUTION)
                # Find which block had the best contribution for debug info
                best_label = ""
                best_weight = 0.0
                for label, weight, is_whole, _src in matches:
                    if is_whole and weight * idf >= best - 1e-9:
                        best_label = label
                        best_weight = weight
                        break
                breakdown["tokens"].append({
                    "token": token,
                    "idf": round(idf, 3),
                    "best_block": best_label,
                    "best_weight": best_weight,
                    "blocks_matched": len(contributions),
                    "contrib": round(token_score, 3),
                })
                breakdown["total"] += token_score

            elif len(token) >= 3:
                for label, weight, is_whole, src in matches:
                    if is_whole or (
                        any(w.startswith(token) for w in src)
                        if isinstance(src, set)
                        else cls._prefix_word(token, src)
                    ):
                        contribution = cls.PREFIX_MULTIPLIER * weight * idf
                        if token in is_identifier:
                            contribution = min(
                                contribution * cls.IDENTIFIER_MULTIPLIER,
                                cls.MAX_IDENTIFIER_TOKEN_CONTRIBUTION,
                            )
                        breakdown["tokens"].append({
                            "token": token,
                            "idf": round(idf, 3),
                            "best_block": label,
                            "best_weight": weight,
                            "blocks_matched": 0,
                            "contrib": round(contribution, 3),
                            "prefix": True,
                        })
                        breakdown["total"] += contribution
                        break

            # 4. Small BIDS-vocabulary identity bonus (damped by rarity).
            if token in cls.BIDS_TERMS and cls._whole_word(token, identity_text):
                bonus = cls.BIDS_IDENTITY_BONUS * min(idf, 1.5)
                breakdown["tokens"].append({
                    "token": token,
                    "idf": round(idf, 3),
                    "best_block": "identity",
                    "best_weight": 0.0,
                    "blocks_matched": 0,
                    "contrib": round(bonus, 3),
                    "bids_identity": True,
                })
                breakdown["total"] += bonus

        # -- 5. Phrase bonus ---------------------------------------------------
        norm_phrase = KnowledgeRecord._normalize(phrase_source)
        if norm_phrase:
            if not phrase_text:
                phrase_text = KnowledgeRecord._normalize(
                    " ".join([record.title, record.summary, record.retrieval_text])
                )
            # Only reward meaningful phrases (>= 8 normalized chars), so
            # "must" / "the" style noise never triggers the bonus.
            if norm_phrase in phrase_text and len(norm_phrase) >= 8:
                breakdown["phrases"].append({
                    "phrase": phrase_source.strip()[:60],
                    "bonus": cls.PHRASE_BONUS,
                })
                breakdown["total"] += cls.PHRASE_BONUS

        breakdown["total"] = round(breakdown["total"], 3)
        return breakdown

    @staticmethod
    def _match_variants(token: str) -> Tuple[str, ...]:
        """
        Variants of a query token used for matching, so that common
        BIDS plurals are treated as the same term:
        ``files -> (files, file)``, ``entities -> (entities, entity)``.
        """
        if token.endswith("s") and len(token) >= 4:
            return (token, token[:-1])
        return (token,)

    @staticmethod
    def _whole_word(token: str, text: str) -> bool:
        return re.search(rf"\b{re.escape(token)}\b", text) is not None

    @staticmethod
    def _prefix_word(token: str, text: str) -> bool:
        return re.search(rf"\b{re.escape(token)}[a-z0-9]*", text) is not None

    @staticmethod
    def _phrase_present(phrase: str, text: str) -> bool:
        """Whole-word phrase match on normalized (``[a-z0-9 ]``) text."""
        return re.search(rf"\b{re.escape(phrase)}\b", text) is not None


# ====================================================================
# Formatter — record -> LLM-friendly text
# ====================================================================


class Formatter:
    """
    Formats a KnowledgeRecord into readable text for LLM consumption.

    Uses only fields that actually exist in the knowledge base schema.
    """

    RAW_CONTENT_LIMIT = 600

    @classmethod
    def format(
        cls,
        record: KnowledgeRecord,
        index: int,
        source_category: str = "",
    ) -> str:
        parts: List[str] = []
        parts.append(f"=== Knowledge Item {index} ===")
        parts.append(f"ID: {record.id}")
        parts.append(f"Type: {record.knowledge_type}")

        # Provenance (actual schema: source.file / section / key)
        src = record.source
        src_file = src.get("file", "")
        src_section = src.get("section", "")
        src_key = src.get("key", "")
        src_parts = [str(src_file)] if src_file else ["unknown"]
        if src_section:
            src_parts.append(f"section: {src_section}")
        if src_key:
            src_parts.append(f"key: {src_key}")
        parts.append(f"Source: {', '.join(src_parts)}")
        if source_category:
            parts.append(f"Source Category: {source_category}")
        if record.bids_version:
            parts.append(f"BIDS Version: {record.bids_version}")
        if record.schema_version:
            parts.append(f"Schema Version: {record.schema_version}")

        parts.append("")
        if record.title:
            parts.append(f"Title: {record.title}")
        if record.summary:
            parts.append(f"Summary: {record.summary}")
        if record.retrieval_text:
            parts.append(f"Description: {record.retrieval_text}")

        if record.requirements is not None:
            parts.append(f"Requirements: {cls._fmt(record.requirements)}")
        if record.conditions:
            parts.append(f"Conditions: {cls._fmt(record.conditions)}")
        if record.allowed_values:
            parts.append(f"Allowed Values: {cls._fmt(record.allowed_values)}")
        if record.expression:
            parts.append(f"Expression: {record.expression}")
        if record.severity:
            parts.append(f"Severity: {record.severity}")
        if record.unit:
            parts.append(f"Unit: {record.unit}")

        scope_text = cls._fmt_scope(record.scope)
        if scope_text:
            parts.append(f"Scope: {scope_text}")

        if record.raw_content:
            raw_str = json.dumps(record.raw_content, ensure_ascii=False)
            if len(raw_str) > cls.RAW_CONTENT_LIMIT:
                raw_str = raw_str[: cls.RAW_CONTENT_LIMIT] + "..."
            parts.append(f"Raw Content: {raw_str}")

        parts.append("")
        return "\n".join(parts)

    # -- value formatting -----------------------------------------------

    @staticmethod
    def _fmt(value: Any) -> str:
        if value is None:
            return ""
        if isinstance(value, str):
            return value
        if isinstance(value, list):
            return "; ".join(Formatter._fmt(v) for v in value)
        if isinstance(value, dict):
            return ", ".join(
                f"{k}: {Formatter._fmt(v)}" for k, v in value.items()
            )
        return str(value)

    @staticmethod
    def _fmt_scope(scope: Dict[str, Any]) -> str:
        if not scope:
            return ""
        bits: List[str] = []
        for key, value in sorted(scope.items()):
            if isinstance(value, list):
                items = [str(v) for v in value if v not in (None, "")]
                if items:
                    bits.append(f"{key}: {', '.join(items)}")
            elif value not in (None, ""):
                bits.append(f"{key}: {value}")
        return " | ".join(bits)


# ====================================================================
# Retriever — loads the KB once, answers repeated queries
# ====================================================================


class Retriever:
    """
    Loads the JSONL-based BIDS knowledge base and serves keyword queries.

    Parameters
    ----------
    data_dir : str
        Directory containing knowledge.jsonl (and optionally
        relationships.jsonl and sources.jsonl).
    """

    # How many neighbors to consider during relationship expansion.
    MAX_RELATED = 3

    def __init__(self, data_dir: str = "./") -> None:
        self.data_dir = Path(data_dir)

        self.records: List[KnowledgeRecord] = []
        self.blocks: List[List[Tuple[str, str, float]]] = []
        self.identities: List[str] = []
        self.edges: List[RelationshipEdge] = []
        self.source_categories: Dict[str, str] = {}

        # id -> record index (used to resolve relationship endpoints)
        self._index: Dict[str, int] = {}
        # adjacency: record_index -> [(relation, neighbor_index, direction)]
        self._adjacency: Dict[int, List[Tuple[str, int, str]]] = {}
        # term token -> inverse document frequency (computed over the KB)
        self._idf: Dict[str, float] = {}
        # adaptive minimum score for a result to be considered relevant
        self._min_best: float = MIN_BEST_SCORE

        # Candidate pre-filter maps (built in _build_index / _build_inverted_index).
        self._word_records: Dict[str, Set[int]] = {}
        self._vocab: List[str] = []
        self._norm_id_records: Dict[str, List[int]] = {}
        self._code_records: Dict[str, List[int]] = {}
        self._severity_records: Dict[str, List[int]] = {}
        self._title_norm: List[str] = []
        # per-record caches fed to Scorer.explain (see _build_inverted_index)
        self._precomputed: List[Dict[str, Any]] = []

        self._load_knowledge()
        self._load_relationships()
        self._load_sources()
        self._build_index()

    # -- Loading --------------------------------------------------------

    def _load_knowledge(self) -> None:
        path = self.data_dir / KNOWLEDGE_FILE
        if not path.exists():
            logger.warning("knowledge.jsonl not found at %s", path)
            return

        loaded, skipped = 0, 0
        try:
            with open(path, "r", encoding="utf-8") as f:
                for line_no, line in enumerate(f, 1):
                    line = line.strip()
                    if not line:
                        continue
                    try:
                        data = json.loads(line)
                        if not isinstance(data, dict) or not data.get("id"):
                            raise ValueError("record has no 'id' field")
                        self.records.append(KnowledgeRecord(data))
                        loaded += 1
                    except (json.JSONDecodeError, ValueError) as exc:
                        skipped += 1
                        logger.warning(
                            "Skipping malformed line %d of %s: %s",
                            line_no, path.name, exc,
                        )
        except (OSError, UnicodeDecodeError) as exc:
            logger.error("Failed to read %s: %s", path, exc)
            self.records.clear()
            return

        logger.info("Loaded %d records (%d skipped) from %s", loaded, skipped, path.name)

    def _load_relationships(self) -> None:
        path = self.data_dir / RELATIONSHIPS_FILE
        if not path.exists():
            logger.info("relationships.jsonl not found; relationship expansion disabled.")
            return
        for line_no, line in enumerate(self._read_lines(path), 1):
            try:
                data = json.loads(line)
                if isinstance(data, dict) and data.get("source") and data.get("target"):
                    self.edges.append(RelationshipEdge(data))
            except json.JSONDecodeError:
                logger.warning("Skipping malformed relationship line %d of %s", line_no, path.name)
        logger.info("Loaded %d relationships from %s", len(self.edges), path.name)

    def _load_sources(self) -> None:
        """Load sources.jsonl into a normalized source_path -> category map."""
        path = self.data_dir / SOURCES_FILE
        if not path.exists():
            return
        for line_no, line in enumerate(self._read_lines(path), 1):
            try:
                data = json.loads(line)
                sp = data.get("source_path", "")
                if sp and data.get("category"):
                    self.source_categories[sp.replace("\\", "/")] = str(data["category"])
            except json.JSONDecodeError:
                logger.warning("Skipping malformed source line %d of %s", line_no, path.name)

    @staticmethod
    def _read_lines(path: Path) -> List[str]:
        try:
            with open(path, "r", encoding="utf-8") as f:
                return [ln.strip() for ln in f if ln.strip()]
        except (OSError, UnicodeDecodeError) as exc:
            logger.error("Failed to read %s: %s", path, exc)
            return []

    # -- Indexing -------------------------------------------------------

    def _build_index(self) -> None:
        self.blocks = [r.build_search_blocks() for r in self.records]
        self.identities = [r.identity_text() for r in self.records]
        self._index = {r.id: i for i, r in enumerate(self.records)}

        # Adjacency over edges whose BOTH endpoints resolve to records.
        # (Many relationship nodes are group placeholders that are not
        # themselves knowledge records; those edges are skipped.)
        for edge in self.edges:
            s_idx = self._index.get(edge.source)
            t_idx = self._index.get(edge.target)
            if s_idx is None or t_idx is None:
                continue
            self._adjacency.setdefault(s_idx, []).append((edge.relation, t_idx, "out"))
            self._adjacency.setdefault(t_idx, []).append((edge.relation, s_idx, "in"))

        # IDF map: common boilerplate terms (must/should/field/...) are
        # damped so that specific technical terms dominate the ranking.
        # IDF is capped so very rare tokens cannot single-handedly dominate
        # a record's score (the raw log values reach ~7.0 on this KB).
        word_re = re.compile(r"[a-z0-9]+")
        df = Counter()
        for blocks in self.blocks:
            seen = set()
            for _label, text, _weight in blocks:
                seen.update(
                    t for t in word_re.findall(text)
                    if t not in Scorer.STOPWORDS and t not in Scorer.GENERIC_TERMS
                )
            df.update(seen)
        n = max(len(self.records), 1)
        self._idf = {
            token: min(3.0, max(0.2, math.log((n + 1) / (count + 1))))
            for token, count in df.items()
        }
        self._min_best = min(MIN_BEST_SCORE, max(0.5, n * 0.005))

        # Inverted index for candidate pre-filtering (see _candidate_indices).
        self._build_inverted_index()

        logger.info("Built index: %d records, %d resolvable adjacency entries",
                    len(self.records), sum(len(v) for v in self._adjacency.values()))

    def _build_inverted_index(self) -> None:
        """
        Precompute per-token and per-structured-component record maps.

        These make each query candidate-driven instead of scanning all
        records, while preserving the exact scoring semantics of
        ``Scorer.score`` because every record the scorer could score
        above zero is included in the candidate set (see
        ``_candidate_indices``).
        """
        word_re = re.compile(r"[a-z0-9]+")
        word_records: Dict[str, Set[int]] = {}
        vocab: Set[str] = set()
        for idx, blocks in enumerate(self.blocks):
            words: Set[str] = set()
            for _label, text, _weight in blocks:
                words.update(word_re.findall(text))
            vocab.update(words)
            for w in words:
                word_records.setdefault(w, set()).add(idx)

        norm_id_records: Dict[str, List[int]] = {}
        code_records: Dict[str, List[int]] = {}
        severity_records: Dict[str, List[int]] = {}
        titles_norm: List[str] = []
        for idx, rec in enumerate(self.records):
            titles_norm.append(KnowledgeRecord._normalize(rec.title))
            rid = KnowledgeRecord._normalize(rec.id)
            norm_id_records.setdefault(rid, []).append(idx)
            if isinstance(rec.requirements, dict):
                code = rec.requirements.get("code")
                if code:
                    norm = KnowledgeRecord._normalize(str(code))
                    code_records.setdefault(norm, []).append(idx)
            sev = str(rec.severity or "").lower().strip()
            if sev:
                severity_records.setdefault(sev, []).append(idx)

        self._word_records = word_records
        self._vocab: List[str] = sorted(vocab)
        self._norm_id_records = norm_id_records
        self._code_records = code_records
        self._severity_records = severity_records
        self._title_norm = titles_norm

        # Per-record lookup caches so scoring a candidate never re-normalizes
        # or re-tokenizes the same record (see Scorer.explain: ``precomputed``).
        precomputed: List[Dict[str, Any]] = []
        for idx, rec in enumerate(self.records):
            rec_block_words = [
                set(word_re.findall(text)) for _label, text, _weight in self.blocks[idx]
            ]
            rec_title = KnowledgeRecord._normalize(rec.title)
            rec_id = KnowledgeRecord._normalize(rec.id)
            rec_summary = KnowledgeRecord._normalize(rec.summary)
            precomputed.append({
                "block_words": rec_block_words,
                "phrase_text": KnowledgeRecord._normalize(
                    " ".join([rec.title, rec.summary, rec.retrieval_text])
                ),
                "rec_id": rec_id,
                "rec_title": rec_title,
                "rec_summary": rec_summary,
                "title_tokens": set(word_re.findall(rec_title)),
                "id_tokens": set(word_re.findall(rec_id)),
                "summary_tokens": set(word_re.findall(rec_summary)),
            })
        self._precomputed = precomputed

    # -- Retrieval ------------------------------------------------------

    def retrieve(self, query: str, top_k: int = 1) -> str:
        """
        Return the most relevant knowledge items as a formatted string.

        Accepts either a plain natural-language query or a string that
        embeds a serialized issue object (``rule_id:... field:...
        message:...``). Issue queries are parsed into structured components
        so that the rule id / field / severity dominate retrieval.
        """
        return self._retrieve(query or "", top_k=top_k)

    def retrieve_issue(
        self,
        issue: dict,
        user_question: str = "",
        top_k: int = 1,
    ) -> str:
        """
        Return the most relevant knowledge items for a structured issue.

        ``issue`` is the raw issue dict (the BIDS-Manager context object).
        Compared to the string-based ``retrieve``, this avoids the lossy
        string round-trip and gives the scorer exact rule_id / field /
        message / severity components directly.
        """
        structured_query = _issue_structured(issue)
        question = (user_question or "").strip()
        if question:
            structured_query["general_text"] = question
        display = (question + " " if question else "") + json.dumps(
            issue, ensure_ascii=False
        )
        return self._retrieve(display or " ", top_k=top_k,
                              structured_query=structured_query)

    def _retrieve(
        self,
        query: str,
        top_k: int = 1,
        structured_query: Optional[Dict[str, str]] = None,
    ) -> str:
        if not self.records:
            return MSG_EMPTY_KB if self._knowledge_file_exists() else MSG_NO_KB.format(self.data_dir)
        if not query or not query.strip():
            return MSG_EMPTY_QUERY

        if structured_query is None:
            structured_query = _parse_query(query)

        # 1. Candidate pre-filter + scoring.
        candidates = self._candidate_indices(query, structured_query)
        scored = self._score_candidates(query, candidates, structured_query)
        if not scored or scored[0][0] < self._min_best:
            return MSG_NO_MATCH.format(query)

        # 2. Combine base hits with relationship-aware neighbours.
        combined = self._expand_related(query, scored, structured_query)
        combined.sort(key=lambda x: x[0], reverse=True)

        # 3. Select top_k (deduplicated, stable order).
        selected: List[Tuple[float, int]] = []
        seen: Set[int] = set()
        for score, idx in combined:
            if idx in seen:
                continue
            seen.add(idx)
            selected.append((score, idx))
            if len(selected) >= top_k:
                break

        # 4. Format for the LLM.
        chunks = []
        for rank, (_score, idx) in enumerate(selected, 1):
            record = self.records[idx]
            category = self.source_categories.get(
                str(record.source.get("file", "")), ""
            )
            chunks.append(Formatter.format(record, rank, category))

        return "\n".join(chunks)

    # -- Candidate pre-filtering -----------------------------------------

    def _candidate_indices(
        self,
        query: str,
        structured_query: Optional[Dict[str, str]] = None,
    ) -> Set[int]:
        """
        Return the record indices that can possibly score > 0 for ``query``.

        This is a strict superset: every record that ``Scorer.score``
        would score above zero is included. Unnecessary extra records are
        simply discarded when the scorer runs on them (score == 0).
        """
        candidates: Set[int] = set()

        tokens, _identifier_tokens, _phrase = Scorer.query_terms(
            query, structured_query
        )
        for token in tokens:
            for v in Scorer._match_variants(token):
                candidates.update(self._word_records.get(v, ()))
            if len(token) >= 3:
                candidates |= self._prefix_records(token)

        if structured_query:
            sq = structured_query

            # Structured rule_id exact matches (code, id, title substring).
            rule_id = KnowledgeRecord._normalize(sq.get("rule_id", "")).strip()
            if rule_id:
                candidates.update(self._code_records.get(rule_id, ()))
                candidates.update(self._norm_id_records.get(rule_id, ()))
                # Substring in normalised titles — O(N) but titles are short;
                # this is fast for the current KB size and cheap to keep exact.
                for i, title in enumerate(self._title_norm):
                    if rule_id in title:
                        candidates.add(i)

            # Structured field phrase / token-set matches: records containing
            # every field token (a superset of the phrase/identity bonuses).
            field = KnowledgeRecord._normalize(sq.get("field", "")).strip()
            if field:
                field_tokens = Scorer.tokenize(field)
                if field_tokens:
                    groups = [self._word_records.get(t, ()) for t in field_tokens]
                    if all(groups):
                        field_set = set(groups[0])
                        for g in groups[1:]:
                            field_set &= g
                        candidates.update(field_set)

            # Severity match.
            severity = (sq.get("severity") or "").lower().strip()
            if severity:
                expect = "error" if severity == "err" else severity
                candidates.update(self._severity_records.get(expect, ()))

        return candidates

    def _prefix_records(self, token: str) -> Set[int]:
        """Records whose blocks contain a word beginning with *token*."""
        out: Set[int] = set()
        for word in self._vocab:
            if word.startswith(token):
                out.update(self._word_records.get(word, ()))
        return out

    # -- Scoring internals ----------------------------------------------

    def _score_candidates(
        self,
        query: str,
        candidate_indices: Set[int],
        structured_query: Optional[Dict[str, str]] = None,
    ) -> List[Tuple[float, int]]:
        """
        Score only the candidate records (see ``_candidate_indices``).

        Candidates are scored in ascending index order and the result kept
        stable, so exact score ties are resolved exactly like a full scan
        (in record index order) instead of depending on set iteration order.
        """
        scored: List[Tuple[float, int]] = []
        for idx in sorted(candidate_indices):
            s = Scorer.score(
                query, self.records[idx], self.blocks[idx],
                self.identities[idx], self._idf,
                structured_query=structured_query,
                precomputed=self._precomputed[idx],
            )
            if s > 0:
                scored.append((s, idx))
        scored.sort(key=lambda x: x[0], reverse=True)
        return scored

    def _expand_related(
        self,
        query: str,
        scored: List[Tuple[float, int]],
        structured_query: Optional[Dict[str, str]] = None,
    ) -> List[Tuple[float, int]]:
        """
        Relationship-aware enrichment.

        For the top results, follow relationships.jsonl edges to neighbours
        and add a small *capped* bonus to neighbours that are themselves
        relevant to the query (their own score > 0).

        The bonus is proportional to the anchor's relevance and capped far
        below the best direct score, so a relationship edge can never lift
        an unrelated neighbour above a genuinely relevant direct result:
        the neighbour must still earn its own relevance.
        """
        if not self.edges or not scored:
            return list(scored)

        best_score = scored[0][0]
        # A neighbour can never receive more than this on top of its own
        # relevance (10% of the best direct score).
        max_bonus = best_score * 0.10
        additions: Dict[int, float] = {}

        for score, idx in scored[: self.MAX_RELATED]:
            for _relation, neighbor_idx, _direction in self._adjacency.get(idx, ()):
                if neighbor_idx in additions:
                    continue
                n_score = Scorer.score(
                    query,
                    self.records[neighbor_idx],
                    self.blocks[neighbor_idx],
                    self.identities[neighbor_idx],
                    self._idf,
                    structured_query=structured_query,
                    precomputed=self._precomputed[neighbor_idx],
                )
                if n_score <= 0:
                    continue
                # Bonus grows with the anchor's relevance but stays a small
                # fraction of the best direct score.
                bonus = min(score * 0.15, max_bonus)
                additions[neighbor_idx] = n_score + bonus

        combined: List[Tuple[float, int]] = list(scored)
        combined.extend((s, i) for i, s in additions.items())
        combined.sort(key=lambda x: x[0], reverse=True)
        return combined

    # -- Debugging / evaluation -----------------------------------------

    def explain(
        self,
        query: str,
        top_k: int = 5,
        record_id: Optional[str] = None,
    ) -> str:
        """
        Return a human-readable score breakdown for the top ``top_k``
        records (or a single named record) so retrieval decisions can be
        audited.

        Useful to inspect *why* a record scored the way it did - e.g. to
        confirm that an exact rule-id match dominates generic word matches.
        """
        if not self.records:
            return "Knowledge base is empty."

        structured_query = _parse_query(query)
        lines: List[str] = []
        lines.append(f"Query: {query}")
        lines.append(f"Parsed issue: {json.dumps(structured_query, ensure_ascii=False)}")
        lines.append("")

        if record_id is not None:
            idx = self._index.get(record_id)
            if idx is None:
                return f"No record with id '{record_id}'."
            targets = [(idx, None)]
        else:
            candidates = self._candidate_indices(query, structured_query)
            scored = self._score_candidates(query, candidates, structured_query=structured_query)
            targets = [(i, s) for s, i in scored[:top_k]]

        for rank, (idx, known_score) in enumerate(targets, 1):
            record = self.records[idx]
            bd = Scorer.explain(
                query, record, self.blocks[idx], self.identities[idx],
                self._idf, structured_query=structured_query,
                precomputed=self._precomputed[idx],
            )
            lines.append(f"--- Rank {rank} ---")
            lines.append(f"Record: {record.id}")
            lines.append(f"Title: {record.title}")
            lines.append(f"Final score: {bd['total']}")
            for st in bd["structured"]:
                lines.append(f"  [structured] {st['type']:<20s} +{st['bonus']}  {st['details']}")
            for tk in bd["tokens"]:
                extra = "prefix" if tk.get("prefix") else (
                    "bids-identity" if tk.get("bids_identity")
                    else f"{tk['blocks_matched']} block(s)"
                )
                lines.append(
                    f"  [token {tk['token']:<16s}] idf={tk['idf']:<5} "
                    f"best={tk['best_block']}(w={tk['best_weight']}) {extra:>12s} {tk['contrib']:+}"
                )
            for ph in bd["phrases"]:
                lines.append(f"  [phrase] {ph['phrase']!r} +{ph['bonus']}")
            if not bd["structured"] and not bd["tokens"] and not bd["phrases"]:
                lines.append("  (no matches)")
            lines.append("")

        return "\n".join(lines)

    def _knowledge_file_exists(self) -> bool:
        return (self.data_dir / KNOWLEDGE_FILE).exists()

    # -- Introspection (kept for compatibility) -------------------------

    def get_record_count(self) -> int:
        return len(self.records)

    def get_record_types(self) -> Dict[str, int]:
        counts: Dict[str, int] = {}
        for rec in self.records:
            counts[rec.knowledge_type] = counts.get(rec.knowledge_type, 0) + 1
        return counts